# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

resources:
 repositories:
   - repository: self
     trigger: none 

stages:
  - stage: Build 
    displayName: build dotnet core solution
    jobs:
      - job: Build
        pool:
          vmImage: ubuntu-latest
        steps:
        - checkout: self
          fetchDepth: 0
        - task: DotNetCoreCLI@2
          displayName: Restore
          inputs:
            command: restore
            projects: '**/*.sln'
            feedsToUse: 'select'
        - task: SonarCloudPrepare@1
          inputs:
            SonarCloud: 'SonarSC'
            